#server:
#  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.3.14:23008/stellaris-spring-dev?characterEncoding=utf8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://47.103.58.94:33060/stellaris?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 159357zx/C
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      # 不能小于30秒，否则默认回到1800秒
      max-lifetime: 30000
      connection-test-query: SELECT 1
  #    druid:
  #      connection-init-sqls: ["SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"]
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update